#!/usr/bin/env python3
"""Pull / build Shopstack images for runtime=compose (cross-platform).

Usage:
  uv run python scripts/pull_images.py
  uv run python scripts/pull_images.py --write-digests
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def load_pins(pin_file: Path) -> dict[str, str]:
    pins: dict[str, str] = {}
    if not pin_file.exists():
        return pins
    for line in pin_file.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        pins[k.strip()] = v.strip().strip('"').strip("'")
    return pins


def run(cmd: list[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    print("+", " ".join(cmd), flush=True)
    return subprocess.run(cmd, check=check, text=True, capture_output=False)


def image_digest(docker: str, image: str) -> str | None:
    """Return repo digest for a local image if available."""
    # Prefer RepoDigests from inspect
    r = subprocess.run(
        [
            docker,
            "image",
            "inspect",
            image,
            "--format",
            "{{json .RepoDigests}}",
        ],
        capture_output=True,
        text=True,
    )
    if r.returncode != 0:
        return None
    text = (r.stdout or "").strip()
    # e.g. ["postgres@sha256:abc..."]
    m = re.search(r"sha256:[a-f0-9]{64}", text)
    if not m:
        # fall back to Id
        r2 = subprocess.run(
            [docker, "image", "inspect", image, "--format", "{{.Id}}"],
            capture_output=True,
            text=True,
        )
        if r2.returncode != 0:
            return None
        mid = re.search(r"sha256:[a-f0-9]{64}", r2.stdout or "")
        return mid.group(0) if mid else None
    return m.group(0)


def strip_digest(ref: str) -> str:
    if "@sha256:" in ref:
        return ref.split("@", 1)[0]
    return ref


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Pull/build Cascade Shopstack images")
    parser.add_argument(
        "--write-digests",
        action="store_true",
        help="Rewrite image-pins.env with @sha256 digests for base images",
    )
    parser.add_argument("--docker", default="docker", help="docker binary")
    parser.add_argument("--skip-build", action="store_true", help="Only pull base images")
    args = parser.parse_args(argv)

    root = repo_root()
    shop = root / "scenarios" / "shopstack"
    pin_file = shop / "image-pins.env"
    pins = load_pins(pin_file)
    if not pins:
        print(f"No pins found at {pin_file}", file=sys.stderr)
        return 1

    # Daemon check
    try:
        subprocess.run([args.docker, "info"], check=True, capture_output=True)
    except Exception as exc:  # noqa: BLE001
        print(f"Docker daemon not available: {exc}", file=sys.stderr)
        return 2

    base_keys = ("CASCADE_POSTGRES_IMAGE", "CASCADE_REDIS_IMAGE")
    for key in base_keys:
        image = pins.get(key)
        if not image:
            continue
        pull_ref = strip_digest(image)
        run([args.docker, "pull", pull_ref])

    if not args.skip_build:
        # Build api/worker via compose so tags match pins
        api = pins.get("CASCADE_API_IMAGE", "cascade/shopstack-api:dev")
        worker = pins.get("CASCADE_WORKER_IMAGE", "cascade/shopstack-worker:dev")
        import os

        env = os.environ.copy()
        env["CASCADE_API_IMAGE"] = strip_digest(api)
        env["CASCADE_WORKER_IMAGE"] = strip_digest(worker)
        # dummy workspace for build-only (compose validates var)
        env["CASCADE_WORKSPACE"] = str((shop / "workspace_template").resolve().as_posix())
        env["CASCADE_EPISODE_ID"] = "pull_images"
        env["CASCADE_CREATED_AT"] = "0"
        compose_file = shop / "docker-compose.yml"
        cmd = [
            args.docker,
            "compose",
            "-f",
            str(compose_file),
            "-p",
            "cascade_pull_images",
            "build",
            "api",
            "worker",
        ]
        print("+", " ".join(cmd), flush=True)
        subprocess.run(cmd, check=True, cwd=str(shop), env=env)

    if args.write_digests:
        new_lines: list[str] = [
            "# Base image pins for Shopstack compose (PR4b).",
            "# Generated by scripts/pull_images.py --write-digests",
            "#",
            "# CASCADE_API_IMAGE / CASCADE_WORKER_IMAGE are built locally (not pulled).",
            "",
        ]
        for key in (
            "CASCADE_POSTGRES_IMAGE",
            "CASCADE_REDIS_IMAGE",
            "CASCADE_API_IMAGE",
            "CASCADE_WORKER_IMAGE",
        ):
            image = pins.get(key, "")
            if key in base_keys:
                tag = strip_digest(image)
                digest = image_digest(args.docker, tag)
                if digest:
                    # repo name without tag for digest form: postgres:16-alpine@sha256:...
                    new_lines.append(f"{key}={tag}@{digest}")
                else:
                    new_lines.append(f"{key}={tag}")
            else:
                new_lines.append(f"{key}={strip_digest(image)}")
        pin_file.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
        print(f"Wrote digests to {pin_file}")

    print("pull_images complete")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
